KVSlab/VaMPy

docs/source/getting_started.rst

- Shorten the time spent running the demonstration scripts for Artery.py
- Runs only 100 timesteps

Shorten demo time

---

simulation/Artery.py

@KristianValen-Sendstad Do you want to add a revised version of the problem description?

Improved Artery.py comments

---

automatedPostProcessing/compute_flow_and_simulation_metrics.py

It is useful to have timer like we have in Oasis so that we can estimate the total computing time and the scalability.
If this seems convenient, please merge them ! 
Any opinions/ suggestions are welcomed.
Kei

added timer inside loop for all the variables.

---

automatedPostProcessing/compute_flow_and_simulation_metrics.py

‘compute_flow_and_simulation_metrics.py’ can accept 2D case now.

updated to allow 2D case

---

docs/source/installation.rst

- Added detailed installations for Linux distros to fix compatibility issues

Update installations for Linux

---

automatedPostProcessing/compute_flow_and_simulation_metrics.py
automatedPostProcessing/compute_hemodynamic_indices.py
automatedPostProcessing/postprocessing_common.py
automatedPostProcessing/visualize_probes.py
docs/source/getting_started.rst
docs/source/installation.rst

- Add scipy dep. to documentation. 
- Refactor viz_probes to not rely on #cycles
- Fixed commands in documentation-
- Removed `no_of_cycles` as input param
Fixes issue #50

Update documentation 

---

automatedPostProcessing/compute_flow_and_simulation_metrics.py
automatedPostProcessing/compute_hemodynamic_indices.py
automatedPostProcessing/postprocessing_common.py
automatedPostProcessing/visualize_probes.py

- Add probe frequency input parameter
- Refactor probe visualization
- Fixes #52

Update probe visualization

---

Atrium.py

Some suggestions on Atrium.py @ehsannkh

Suggesting some changes in Atrium.py

---

.circleci/config.yml
README.md
docs/source/getting_started.rst
docs/source/installation.rst

- Update documentation, README, and CI to install morphman from conda-forge

Install morphMan from conda-forge

---

automatedPreProcessing/README.md
automatedPreProcessing/automatedPreProcessing.py
automatedPreProcessing/simulate.py
automatedPreProcessing/ssh_config.json
test/Case_test_artery/artery_job.sh

- Update SSH config for automatically uploading mesh, starting simulation, and performing post-processing on Saga

Update SSH config

---

automatedPostProcessing/compute_flow_and_simulation_metrics.py
automatedPostProcessing/compute_hemodynamic_indices.py
automatedPostProcessing/compute_velocity_and_pressure.py
automatedPostProcessing/postprocessing_common.py
automatedPostProcessing/visualize_probes.py
docs/source/getting_started.rst
test/test_compute_flow_and_simulation_metrics.py
test/test_compute_velocity_and_pressure.py
test/test_visualize_probes.py

Convert velocity and pressure to visualizable format

---

.circleci/config.yml
automatedPreProcessing/automatedPreProcessing.py

- Removed deprecated length parameter from centerline tolerance method call

Remove length param from tolerance call

---

.gitignore

Hi, 
Very minor stuff, but I thought it would be nice to add mesh and result files into gitignore. 
Best,
Kei

added mesh and result files to gitignore

---

automatedPostProcessing/compute_hemodynamic_indices.py

Fix: #60 
Because dabla function was not running properly with MPI, it is removed now. 
We use basic FEniCS functions to compute the magnitude of several vectors. 
I have not tested on Saga but I think it should work...

removed dabla function

---

automatedPostProcessing/compute_flow_and_simulation_metrics.py
automatedPostProcessing/compute_hemodynamic_indices.py
automatedPostProcessing/compute_velocity_and_pressure.py
automatedPostProcessing/postprocessing_common.py
automatedPostProcessing/visualize_probes.py
test/test_compute_flow_and_simulation_metrics.py
test/test_compute_hemodynamc_indices.py
test/test_compute_velocity_and_pressure.py

- Added sample step size parameter used to determine the number of sampled points during post-processing
- Updated tests with additional parameter
- Computed start time step for hemodynamic values based on `T`, `dt` and `save_frequency`

Add sample step size parameter

---

src/vampy/automatedPreProcessing/automatedPreProcessing.py
src/vampy/automatedPreProcessing/preprocessing_common.py

- Add --add-boundary-layers parameter
- Add flag for turning on/off boundary layers

Add option to ignore boundary layers

---

docs/preprocess.md
src/vampy/automatedPreprocessing/automated_preprocessing.py
src/vampy/automatedPreprocessing/preprocessing_common.py

- Add `scale_surface` method for scaling between units (to mm)
- Reorder sections in pre-processing docs chronologically

Add scaling method

---

README.md
docs/_toc.yml
docs/conda.md
docs/docker.md
docs/installation.md

* Clarify installation instructions for installing with Docker and conda.
* Emphasize dependencies, Python version support, and supporting operating systems in documentation. 
* Connected to issue #104

Update installation instructions

---

docs/issues.md
src/vampy/automatedPreprocessing/preprocessing_common.py

* Add local support for `vtkvmtkDolfinWriter` instead of relying on user interaction for fixing issue.

Hotfix compress mesh

---

docs/preprocess.md
docs/simulation.md

Hi, this PR fixes some minor issues in the documentation.

Fix typo's in documentation

---

docs/installation.md

Add VMTK as VaMPy dependency

---

src/vampy/automatedPreprocessing/automated_preprocessing.py
src/vampy/automatedPreprocessing/preprocessing_common.py
tests/test_pre_processing.py

* Add resampling_step as parameter
* For single outlet models - clip CL before entering wall
* Update single outlet test

Add resampling step as parameter

---

.github/workflows/check_and_test_package.yml
docs/preprocess.md
src/vampy/automatedPostprocessing/compute_flow_and_simulation_metrics.py
src/vampy/automatedPostprocessing/postprocessing_common.py

* Refactor flow metrics code
* Fix stepping for phase averaging computation
* Extract phase- and cycle-averaging steps into separate methods for improved readabiltiy

Improvements to flow metrics computation.

---

src/vampy/automatedPreprocessing/automated_preprocessing.py
src/vampy/automatedPreprocessing/preprocessing_common.py
tests/test_pre_processing.py

- Flips flow extension lengths (-fli,-flo) for atrium models

Update to flow extension modeling

---

src/vampy/automatedPreprocessing/automated_preprocessing.py
src/vampy/automatedPreprocessing/preprocessing_common.py

This pull request adds a new option `--flow-rate-factor` that makes it possible to change the flow rate factor. Default is `0.27` as before.

Add option to specify flow rate factor

---

src/vampy/automatedPreprocessing/automated_preprocessing.py
src/vampy/automatedPreprocessing/preprocessing_common.py
src/vampy/simulation/Artery.py
src/vampy/simulation/Atrium.py

Related to #123 
Additionally, I propose that we switch to using `json` for saving probe points. I think it’s better that we can just open the file with text-editor and see if the probe points are within reasonable range. 
Feel free to let me know what you think! @hkjeldsberg @johannesring

rescale resampling step and switch to json for saving probe points

---

src/vampy/automatedPreprocessing/automated_preprocessing.py
src/vampy/automatedPreprocessing/preprocessing_common.py

- Use network splitting for arteries with more than one outlet, else area split for BCs

Update to Network BCs

---

src/vampy/automatedPostprocessing/compute_velocity_and_pressure.py
src/vampy/automatedPostprocessing/postprocessing_common.py
src/vampy/simulation/MovingAtrium.py
src/vampy/simulation/Probe.py
tests/test_compute_velocity_and_pressure.py

Update probe import

---

src/vampy/simulation/Womersley.py

CI has been failing due to new scipy syntax. This PR should fix the issue.

update scipy syntax
